---
all:
  children:
    ubuntu_vms:
      hosts:
        ubuntu-1:
          ansible_host: 127.0.0.1
          ansible_port: 2220
          ansible_user: user

          netplan_ssh_mac: "52:54:00:12:34:56"
          netplan_mesh_mac: "52:54:00:12:34:57"
          netplan_mesh_ip: "10.0.0.1/24"

          hashistack_advertise_addr: "10.0.0.1"
          hashistack_consul_server: true
          hashistack_nomad_server: true

        ubuntu-2:
          ansible_host: 127.0.0.1
          ansible_port: 2221
          ansible_user: user

          netplan_ssh_mac: "52:54:00:12:34:58"
          netplan_mesh_mac: "52:54:00:12:34:59"
          netplan_mesh_ip: "10.0.0.2/24"

          hashistack_advertise_addr: "10.0.0.2"
          hashistack_consul_server: true
          hashistack_nomad_server: true

        ubuntu-3:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_user: user

          netplan_ssh_mac: "52:54:00:12:34:5a"
          netplan_mesh_mac: "52:54:00:12:34:5b"
          netplan_mesh_ip: "10.0.0.3/24"

          hashistack_advertise_addr: "10.0.0.3"
          hashistack_consul_server: true
          hashistack_nomad_server: true

        ubuntu-4:
          ansible_host: 127.0.0.1
          ansible_port: 2223
          ansible_user: user

          netplan_ssh_mac: "52:54:00:12:34:5c"
          netplan_mesh_mac: "52:54:00:12:34:5d"
          netplan_mesh_ip: "10.0.0.4/24"

          hashistack_advertise_addr: "10.0.0.4"
          hashistack_consul_client: true
          hashistack_nomad_client: true

      vars:
        ansible_connection: ssh
        # Полезно для локальных ВМ, которые часто пересоздаются.
        # Отключает проверку известных хостов, чтобы не ловить ошибку
        # при изменении host key.
        ansible_ssh_common_args: >-
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null

        hashistack_cluster_servers:
          - "10.0.0.1"
          - "10.0.0.2"
          - "10.0.0.3"

    hashistack_clients:
      hosts:
        nomad-client-1:
          ansible_host: 127.0.0.1
          ansible_port: 2220
          ansible_user: user
          ansible_connection: ssh
          ansible_ssh_common_args: >-
            -o StrictHostKeyChecking=no
            -o UserKnownHostsFile=/dev/null

          hashistack_node_name: "nomad-client-1"
          hashistack_advertise_addr: "10.0.0.1"
          hashistack_network_interface: "eth0"

      vars:
        hashistack_node_role: client
        hashistack_cluster_servers:
          - "10.0.0.1"
          - "10.0.0.2"
          - "10.0.0.3"
