---
- name: Включить и запустить Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
    daemon_reload: true
  become: true

- name: Добавить пользователя nomad в группу docker
  ansible.builtin.user:
    name: nomad
    groups: docker
    append: true
  become: true
  notify: Restart nomad
